### ISSUE TITLE
Allow usage of "QR Scanner (Privacy Friendly)"

### ISSUE THREAD

**Issue by ligi** [ligi/PassAndroid#277]
suggestion via google play:

![Selection_183](https://user-images.githubusercontent.com/111600/91929764-68e63180-ecdf-11ea-81e3-d3a35447be4a.png)

maybe we can leverage this: https://github.com/zxing/zxing/pull/728/files

**Comment by ioogithub** [comment]
This doesn't work anyway. The scanner app it asks for is already installed and it doesn't detect it.

Currently there is no way to scan an barcode with this app.

**Comment by Nationalgeographic** [comment]
Would prefer "Binary Eye" from F-Droid, or allow to select between scanners.

**Comment by spaetz** [comment]
Is this fixed with the already merged  MR https://github.com/ligi/PassAndroid/pull/364 allowing binary eye?

**Comment by arraintxo** [comment]
Same issue still in version 3.7.3

App keeps asking for "Barcode Scanner" and even installing the app the QR can't be imported to PassAndroid.

I just use BinaryEye and copy the scanned code to PassAndroid
